### ISSUE TITLE
Skeleton of the board

### ISSUE THREAD

**Issue by ldallos** [ldallos/evoLudo#1]
- [x] Create new game window
- [x] Show this game window after starting of application
- [x] Divide the game window into 9 parts

Total: 3 h

**Comment by ilkukrisz** [comment]
I just finished working on this issue. It took about 40minutes for me. Please check my code and if it is okay you can close this issue. If anything is wrong please let me know. Thanks.

**Comment by ldallos** [comment]
It is actually good.
But for example it can not be seen fully on my screen (1366x768).
The dynamic size change could be a further improvement step.

![main_frame](https://user-images.githubusercontent.com/4312457/46884876-93624380-ce56-11e8-83c5-6a3a4c809d62.png)

**Comment by ldallos** [comment]
The issue has been finished. The tasks have been completed. The size of the game window is dynamic.
