### ISSUE TITLE
Control the game

### ISSUE THREAD

**Issue by ldallos** [ldallos/evoLudo#7]
- [x] Dice rolling -> action -> next player
- [x] Token step direction
- [x] Opponent token handling
- [x] End condition of the game

Total: 10 h

**Comment by ilkukrisz** [comment]
Almost everything is added. Needs some testing to detect any issues. I pushed it to #11 branch. The code will be reformatted to be much more readable. About that I got your email, and it is a very good way to go, thanks for the tip.

**Comment by ldallos** [comment]
The tasks have been finished. So I have closed the issue.
